In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


# 1. Read the dataset to the python environment.


In [33]:
data=pd.read_excel("iris.xls")

In [4]:
data.head()

SL   SW   PL   PW Classification
0  5.1  3.5  1.4  0.2    Iris-setosa
1  4.9  3.0  1.4  0.2    Iris-setosa
2  4.7  3.2  1.3  0.2    Iris-setosa
3  4.6  3.1  1.5  0.2    Iris-setosa
4  5.0  3.6  1.4  0.2    Iris-setosa

# 2. Do necessary pre-processing steps.


In [5]:
data.shape

(150, 5)

In [6]:
data.isna().sum

<bound method NDFrame._add_numeric_operations.<locals>.sum of         SL     SW     PL     PW  Classification
0    False  False  False  False           False
1    False  False  False  False           False
2    False  False  False  False           False
3    False  False  False  False           False
4    False  False  False  False           False
..     ...    ...    ...    ...             ...
145  False  False  False  False           False
146  False  False  False  False           False
147  False  False  False  False           False
148  False  False  False  False           False
149  False  False  False  False           False

[150 rows x 5 columns]>

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   SL              150 non-null    float64
 1   SW              150 non-null    float64
 2   PL              150 non-null    float64
 3   PW              150 non-null    float64
 4   Classification  150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [8]:
data.columns

Index(['SL', 'SW', 'PL', 'PW', 'Classification'], dtype='object')

In [9]:
for i in ['SL', 'SW', 'PL']:
    data[i]=data[i].fillna(data[i].median())

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   SL              150 non-null    float64
 1   SW              150 non-null    float64
 2   PL              150 non-null    float64
 3   PW              150 non-null    float64
 4   Classification  150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


# 3. Find out which classification model gives the best result to predict iris species


# a) Linear Regression


In [11]:
x=data[['SL', 'SW', 'PL', 'PW']]
y=data['Classification']   


In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.3)


In [13]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score
confusion_matrix(y_test,y_pred)

array([[19,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 13]], dtype=int64)

In [14]:
accuracy_score(y_test,y_pred)

1.0

In [16]:
f1_score(y_test,y_pred,average='micro')


1.0

# b) KNN


In [17]:
from sklearn.neighbors import KNeighborsClassifier


In [18]:
k_value=[]
neighbors=np.arange(3,10)
for k in neighbors:
    classifier=KNeighborsClassifier(n_neighbors=k,metric='minkowski')
    classifier.fit(x_train,y_train)
    y_pred=classifier.predict(x_test)
    accurate=accuracy_score(y_test,y_pred)
    k_value.append(accurate)
  

In [19]:
k_value


[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

In [20]:
confusion_matrix(y_test,y_pred)


array([[19,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 13]], dtype=int64)

In [21]:
accuracy_score(y_test,y_pred)


1.0

In [22]:
f1_score(y_test,y_pred,average='macro')


1.0

# c) SVM

In [23]:
from sklearn.svm import SVC

# i) Linear SVM

In [24]:
svm=SVC(kernel='linear')
svm.fit(x_train,y_train)
y_pred=svm.predict(x_test)

In [25]:
accuracy_score(y_test,y_pred)

1.0

In [26]:
f1_score(y_test,y_pred,average='macro')

1.0

In [27]:
confusion_matrix(y_test,y_pred)

array([[19,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 13]], dtype=int64)

# ii) Radial SVM

In [28]:
svm_radial=SVC(kernel='rbf')
svm_radial.fit(x_train,y_train)
y_pred=svm_radial.predict(x_test)

In [29]:
accuracy_score(y_test,y_pred)

1.0

In [30]:
f1_score(y_test,y_pred,average='macro')

1.0

In [31]:
confusion_matrix(y_test,y_pred)

array([[19,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 13]], dtype=int64)

# iii) Polynomial SVM

In [34]:
svm=SVC(kernel='poly',degree=2)
svm.fit(x_train,y_train)
y_pred=svm.predict(x_test)

In [35]:
accuracy_score(y_test,y_pred)

1.0

In [36]:
f1_score(y_test,y_pred,average='macro')

1.0

In [37]:
confusion_matrix(y_test,y_pred)

array([[19,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 13]], dtype=int64)

In [38]:
confusion_matrix(y_test,y_pred)

array([[19,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 13]], dtype=int64)

In [39]:
f1_score(y_test,y_pred,average='macro')

1.0

In [40]:
accuracy_score(y_test,y_pred)

1.0

# e) Random Forest

In [41]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)

In [42]:
confusion_matrix(y_test,y_pred)

array([[19,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 13]], dtype=int64)

In [43]:
f1_score(y_test,y_pred,average='macro')

1.0

In [44]:
accuracy_score(y_test,y_pred)

1.0

Identify the important features and build the model using that features

In [45]:
feature_imp=pd.Series(rf.feature_importances_).sort_values(ascending=False)*100

In [46]:
feature_imp

3    43.219634
2    41.361218
0    11.054701
1     4.364447
dtype: float64

In [47]:
x=data[['PL', 'PW']]
y=data['Classification']

In [48]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.3)

In [49]:
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)

In [50]:
confusion_matrix(y_test,y_pred)

array([[19,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 13]], dtype=int64)

In [51]:
accuracy_score(y_test,y_pred)

1.0

In [52]:
f1_score(y_test,y_pred,average='macro')

1.0

# f) Gradient Boosting

In [53]:
x=data[['SL', 'SW', 'PL', 'PW']]
y=data['Classification']  

In [54]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.3)

In [55]:
from sklearn.ensemble import GradientBoostingClassifier
grb=GradientBoostingClassifier()
grb.fit(x_train,y_train)
y_pred=grb.predict(x_test)

In [56]:
accuracy_score(y_test,y_pred)

1.0

In [57]:
f1_score(y_test,y_pred,average='macro')

1.0

From the above we understood that gradient boosting and Random forest classification on important features gave the best result in predicting the species

